#!/usr/bin/env python3
"""Sync selected daily arXiv papers into a Zotero daily collection.

This script is intentionally deterministic and consumes the same JSON input as
``04_daily_paper_brief.py``. The AI only fills the ``selected`` field; this script
does the Zotero side:

1. Resolve unique selected papers with arXiv IDs.
2. Find or import missing papers into Zotero through the Zotero Connector.
3. Attach PDFs for newly imported papers through the Connector, and generate a
   deterministic Zotero-runtime helper when an existing item is missing its PDF.
4. Rebuild ``Arxiv-Daily-Papers/<date>`` with the existing citation keys plus
   the newly selected citation keys through Better BibTeX ``collection.scanAUX``.

It never writes Zotero's SQLite database directly.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import datetime as dt
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


DEFAULT_BASE_URL = os.environ.get("ZOTERO_LOCAL_BASE_URL", "http://127.0.0.1:23119")
LOCAL_USER = "/api/users/0"
API_HEADERS = {"Zotero-API-Version": "3"}
CONNECTOR_HEADERS = {"X-Zotero-Connector-API-Version": "3"}
DEFAULT_ROOT_COLLECTION = "Arxiv-Daily-Papers"
ARXIV_ID_RE = re.compile(r"(?<!\d)(\d{4}\.\d{4,5})(?:v\d+)?(?!\d)")
TEXT_LIMIT = 500
RUNTIME_PDF_SCRIPT_TEMPLATE = """// Generated by 02_sync_selected_papers_to_zotero.py.
// Execute with llm-for-zotero zotero_script mode='write'.
const PLAN = __PLAN_JSON__;

function firstText(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) {
      return value.replace(/\\s+/g, " ").trim();
    }
  }
  return "";
}

function attachmentLooksLikePdf(item, arxivId) {
  const contentType = firstText(item.getField("contentType")).toLowerCase();
  const title = firstText(item.getField("title")).toLowerCase();
  const url = firstText(item.getField("url")).toLowerCase();
  const filename = firstText(item.attachmentFilename).toLowerCase();
  const haystack = [contentType, title, url, filename].join("\\n");
  return contentType === "application/pdf"
    || contentType.endsWith("/pdf")
    || haystack.includes(".pdf")
    || (arxivId && haystack.includes(`/pdf/${arxivId}`));
}

async function parentHasPdf(parent, arxivId) {
  const attachmentIDs = parent.getAttachments();
  for (const attachmentID of attachmentIDs) {
    const attachment = Zotero.Items.get(attachmentID);
    if (attachment && attachmentLooksLikePdf(attachment, arxivId)) {
      return {
        ok: true,
        attachmentID,
        attachmentKey: attachment.key,
        title: attachment.getDisplayTitle()
      };
    }
  }
  return { ok: false };
}

const result = { attached: [], skipped: [], failed: [] };

for (const entry of PLAN) {
  const libraryID = entry.libraryID || env.libraryID || 1;
  const parent = Zotero.Items.getByLibraryAndKey(libraryID, entry.itemKey);
  if (!parent) {
    result.failed.push({ ...entry, error: "PARENT_ITEM_NOT_FOUND" });
    continue;
  }

  const existing = await parentHasPdf(parent, entry.arxivId);
  if (existing.ok) {
    result.skipped.push({ ...entry, reason: "PDF_ALREADY_PRESENT", existing });
    continue;
  }

  try {
    env.snapshot(parent);
    const attachment = await Zotero.Attachments.importFromURL({
      libraryID: parent.libraryID,
      parentItemID: parent.id,
      url: entry.pdfUrl,
      title: "Full Text PDF",
      fileBaseName: `arxiv-${entry.arxivId}`,
      contentType: "application/pdf",
      referrer: entry.referrer || `https://arxiv.org/abs/${entry.arxivId}`
    });
    env.addUndoStep(async () => {
      const created = Zotero.Items.get(attachment.id);
      if (created) {
        await created.eraseTx();
      }
    });
    result.attached.push({
      ...entry,
      attachmentID: attachment.id,
      attachmentKey: attachment.key,
      title: attachment.getDisplayTitle()
    });
  } catch (err) {
    result.failed.push({ ...entry, error: String(err && err.message ? err.message : err) });
  }
}

env.log(JSON.stringify(result, null, 2));
if (result.failed.length) {
  throw new Error(`Failed to attach ${result.failed.length} PDF(s)`);
}
"""


class ZoteroSyncError(RuntimeError):
    def __init__(self, message: str, report: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.report = report


class HttpClient:
    def __init__(self, base_url: str = DEFAULT_BASE_URL, timeout: float = 30.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def url(self, path: str) -> str:
        return self.base_url + path

    def request(
        self,
        path: str,
        *,
        method: str = "GET",
        data: bytes | str | dict[str, Any] | list[Any] | None = None,
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> tuple[int, dict[str, str], str]:
        body: bytes | None = None
        request_headers = dict(headers or {})
        if data is not None:
            if isinstance(data, (dict, list)):
                body = json.dumps(data).encode("utf-8")
                request_headers.setdefault("Content-Type", "application/json")
            elif isinstance(data, str):
                body = data.encode("utf-8")
            else:
                body = data

        try:
            req = urllib.request.Request(
                self.url(path),
                data=body,
                method=method,
                headers=request_headers,
            )
            with urllib.request.urlopen(req, timeout=timeout or self.timeout) as response:
                text = response.read().decode("utf-8", errors="replace")
                return response.status, dict(response.headers.items()), text
        except urllib.error.HTTPError as exc:
            text = exc.read().decode("utf-8", errors="replace")
            raise ZoteroSyncError(f"{method} {path} failed: status={exc.code} body={text[:TEXT_LIMIT]}") from exc
        except Exception as exc:
            raise ZoteroSyncError(f"{method} {path} failed: {exc}") from exc

    def api_json(self, path: str, *, timeout: float | None = None) -> Any:
        api_path = path if path.startswith("/api") else f"/api{path}"
        status, _, text = self.request(api_path, headers=API_HEADERS, timeout=timeout)
        if not (200 <= status < 300):
            raise ZoteroSyncError(f"GET {api_path} failed: status={status}")
        return json.loads(text or "null")

    def api_text_with_headers(self, path: str, *, timeout: float | None = None) -> tuple[str, dict[str, str]]:
        api_path = path if path.startswith("/api") else f"/api{path}"
        status, headers, text = self.request(api_path, headers=API_HEADERS, timeout=timeout)
        if not (200 <= status < 300):
            raise ZoteroSyncError(f"GET {api_path} failed: status={status}")
        return text, headers

    def connector_post(
        self,
        path: str,
        payload: Any,
        *,
        content_type: str = "application/json",
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> tuple[int, dict[str, str], str]:
        request_headers = dict(CONNECTOR_HEADERS)
        request_headers["Content-Type"] = content_type
        if headers:
            request_headers.update(headers)
        data = json.dumps(payload).encode("utf-8") if content_type == "application/json" else payload
        return self.request(path, method="POST", data=data, headers=request_headers, timeout=timeout)

    def bbt_rpc(self, method: str, params: list[Any] | dict[str, Any] | None = None) -> Any:
        payload = {
            "jsonrpc": "2.0",
            "id": f"codex-{int(time.time() * 1000)}",
            "method": method,
            "params": [] if params is None else params,
        }
        status, _, text = self.request(
            "/better-bibtex/json-rpc",
            method="POST",
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        if status != 200:
            raise ZoteroSyncError(f"Better BibTeX JSON-RPC failed: status={status}")
        response = json.loads(text or "{}")
        if response.get("error"):
            raise ZoteroSyncError(f"Better BibTeX {method} failed: {response['error']}")
        return response.get("result")


def dump_json(value: Any) -> None:
    print(json.dumps(value, ensure_ascii=False, indent=2))


def utc_now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def progress_log(enabled: bool, message: str) -> None:
    if enabled:
        print(message, file=sys.stderr, flush=True)


def first_text(*values: Any) -> str:
    for value in values:
        if isinstance(value, str) and value.strip():
            return re.sub(r"\s+", " ", value.strip())
    return ""


def list_text(values: Any) -> str:
    if isinstance(values, list):
        return ", ".join(str(value).strip() for value in values if str(value).strip())
    return first_text(values)


def normalize_arxiv_id(value: str) -> str:
    match = ARXIV_ID_RE.search(value or "")
    return match.group(1) if match else ""


def arxiv_id_from_paper(paper: dict[str, Any]) -> str:
    candidates = [
        first_text(paper.get("id")),
        first_text(paper.get("versionedId")),
        first_text(paper.get("arxivId"), paper.get("arxiv_id")),
        first_text(paper.get("arxivUrl"), paper.get("arxiv_url")),
        first_text(paper.get("pdfUrl"), paper.get("pdf_url")),
        first_text(paper.get("url"), paper.get("link")),
    ]
    for candidate in candidates:
        arxiv_id = normalize_arxiv_id(candidate)
        if arxiv_id:
            return arxiv_id
    return ""


def canonical_key(paper: dict[str, Any]) -> str:
    arxiv_id = arxiv_id_from_paper(paper)
    if arxiv_id:
        return f"arxiv:{arxiv_id}"
    paper_id = first_text(paper.get("id"), paper.get("versionedId"))
    if paper_id:
        return f"id:{re.sub(r'v\\d+$', '', paper_id)}"
    title = first_text(paper.get("title"), paper.get("english_title"), paper.get("title_en"))
    return f"title:{title.lower()}"


def load_json(path: str) -> Any:
    if path == "-":
        return json.load(sys.stdin)
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)


def iter_source_blocks(payload: dict[str, Any]) -> list[dict[str, Any]]:
    sources = payload.get("sources")
    if not isinstance(sources, list):
        raise ValueError("Input JSON must include sources: [{\"source\": ..., \"papers\": [...]}].")
    return [block for block in sources if isinstance(block, dict)]


def flatten_papers(payload: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]], dict[str, dict[str, Any]]]:
    papers: list[dict[str, Any]] = []
    index_lookup: dict[int, dict[str, Any]] = {}
    id_lookup: dict[str, dict[str, Any]] = {}
    key_lookup: dict[str, dict[str, Any]] = {}
    next_index = 1

    for block in iter_source_blocks(payload):
        source = first_text(block.get("source"), block.get("name")) or "unknown"
        for raw_paper in block.get("papers", []):
            if not isinstance(raw_paper, dict):
                continue
            raw_index = raw_paper.get("index", raw_paper.get("idx"))
            try:
                index = int(raw_index) if raw_index is not None else next_index
            except (TypeError, ValueError):
                index = next_index
            next_index = max(next_index, index + 1)

            key = canonical_key(raw_paper)
            if key in key_lookup:
                paper = key_lookup[key]
                paper.setdefault("__indexes", []).append(index)
                if source not in paper.setdefault("__sources", []):
                    paper["__sources"].append(source)
            else:
                paper = dict(raw_paper)
                paper["__index"] = index
                paper["__indexes"] = [index]
                paper["__sources"] = [source]
                key_lookup[key] = paper
                papers.append(paper)

            index_lookup[index] = paper
            for identifier in [
                first_text(raw_paper.get("id")),
                first_text(raw_paper.get("versionedId")),
                arxiv_id_from_paper(raw_paper),
            ]:
                if identifier:
                    id_lookup[identifier] = paper
                    id_lookup[re.sub(r"v\d+$", "", identifier)] = paper

    return papers, index_lookup, id_lookup


def parse_selection_entries(selection_data: Any) -> list[dict[str, Any]]:
    if not selection_data:
        return []
    if isinstance(selection_data, dict):
        entries: list[dict[str, Any]] = []
        for topic, value in selection_data.items():
            values = value if isinstance(value, list) else [value]
            for item in values:
                if isinstance(item, dict):
                    entry = dict(item)
                    entry.setdefault("topic", topic)
                else:
                    entry = {"index": item, "topic": topic}
                entries.append(entry)
        return entries
    if isinstance(selection_data, list):
        return [dict(item) if isinstance(item, dict) else {"index": item} for item in selection_data]
    raise TypeError("Selection must be a list or an object.")


def entry_topics(entry: dict[str, Any]) -> list[str]:
    raw = entry.get("topics")
    if raw is None and entry.get("topic"):
        raw = [entry["topic"]]
    if isinstance(raw, str):
        topics = [raw]
    elif isinstance(raw, list):
        topics = [str(topic).strip() for topic in raw if str(topic).strip()]
    else:
        topics = []

    extra = entry.get("also_topics", entry.get("alsoTopics"))
    if isinstance(extra, str):
        extra = [extra]
    if isinstance(extra, list):
        topics.extend(str(topic).strip() for topic in extra if str(topic).strip())

    deduped: list[str] = []
    for topic in topics:
        if topic not in deduped:
            deduped.append(topic)
    return deduped


def resolve_selected_papers(payload: dict[str, Any], selection_payload: Any | None = None) -> list[dict[str, Any]]:
    _, index_lookup, id_lookup = flatten_papers(payload)
    selection_data = selection_payload
    if selection_data is None:
        selection_data = payload.get("selection", payload.get("selected", payload.get("selected_papers")))

    selected: list[dict[str, Any]] = []
    by_key: dict[str, dict[str, Any]] = {}

    for entry in parse_selection_entries(selection_data):
        paper: dict[str, Any] | None = None
        if "index" in entry:
            try:
                paper = index_lookup.get(int(entry["index"]))
            except (TypeError, ValueError):
                paper = None
        if paper is None and "id" in entry:
            paper = id_lookup.get(str(entry["id"])) or id_lookup.get(normalize_arxiv_id(str(entry["id"])))
        if paper is None and "paper_id" in entry:
            paper = id_lookup.get(str(entry["paper_id"])) or id_lookup.get(normalize_arxiv_id(str(entry["paper_id"])))
        if paper is None:
            continue

        key = canonical_key(paper)
        topics = entry_topics(entry)
        relevance = first_text(entry.get("relevance"), entry.get("reason"), entry.get("why"))

        if key not in by_key:
            item = {"key": key, "paper": paper, "topics": [], "relevances": []}
            by_key[key] = item
            selected.append(item)
        item = by_key[key]
        for topic in topics:
            if topic not in item["topics"]:
                item["topics"].append(topic)
        if relevance and relevance not in item["relevances"]:
            item["relevances"].append(relevance)

    return selected


def extract_bibtex_keys(text: str) -> list[str]:
    return re.findall(r"@\w+\s*\{\s*([^,\s]+)", text)


def make_safe_connector_id(arxiv_id: str) -> str:
    return "codex" + re.sub(r"[^A-Za-z0-9]", "", arxiv_id)


def split_creator(name: str) -> dict[str, str]:
    name = re.sub(r"\s+", " ", name).strip()
    if not name:
        return {"lastName": "Unknown", "creatorType": "author"}
    if "," in name:
        last, first = [part.strip() for part in name.split(",", 1)]
        if first:
            return {"firstName": first, "lastName": last, "creatorType": "author"}
        return {"lastName": last, "creatorType": "author"}
    parts = name.split()
    if len(parts) == 1:
        return {"lastName": parts[0], "creatorType": "author"}
    return {"firstName": " ".join(parts[:-1]), "lastName": parts[-1], "creatorType": "author"}


def creator_dicts(authors: Any) -> list[dict[str, str]]:
    if not isinstance(authors, list):
        return []
    return [split_creator(str(author)) for author in authors if str(author).strip()]


def paper_title(paper: dict[str, Any]) -> str:
    return first_text(paper.get("title"), paper.get("englishTitle"), paper.get("english_title"), paper.get("title_en"))


def paper_summary(paper: dict[str, Any]) -> str:
    return first_text(paper.get("summary"), paper.get("abstract"), paper.get("englishSummary"), paper.get("english_summary"))


def paper_date(paper: dict[str, Any]) -> str:
    value = first_text(paper.get("published"), paper.get("updated"), paper.get("date"))
    match = re.search(r"\d{4}-\d{2}-\d{2}", value)
    return match.group(0) if match else value


def paper_categories(paper: dict[str, Any]) -> list[str]:
    categories = paper.get("categories")
    if isinstance(categories, list):
        values = [str(category).strip() for category in categories if str(category).strip()]
    else:
        values = []
    primary = first_text(paper.get("primaryCategory"), paper.get("primary_category"))
    if primary and primary not in values:
        values.insert(0, primary)
    return values


def paper_arxiv_url(paper: dict[str, Any], arxiv_id: str) -> str:
    return first_text(paper.get("arxivUrl"), paper.get("arxiv_url")) or f"https://arxiv.org/abs/{arxiv_id}"


def paper_pdf_url(paper: dict[str, Any], arxiv_id: str) -> str:
    return first_text(paper.get("pdfUrl"), paper.get("pdf_url")) or f"https://arxiv.org/pdf/{arxiv_id}"


def connector_item_from_paper(paper: dict[str, Any], arxiv_id: str) -> dict[str, Any]:
    categories = paper_categories(paper)
    primary = categories[0] if categories else ""
    extra_lines = [f"arXiv:{arxiv_id}" + (f" [{primary}]" if primary else "")]
    comment = first_text(paper.get("comment"), paper.get("comments"))
    if comment:
        extra_lines.append(f"Comment: {comment}")
    hf_url = first_text(paper.get("huggingFaceUrl"), paper.get("huggingfaceUrl"), paper.get("hfUrl"))
    if hf_url:
        extra_lines.append(f"Hugging Face: {hf_url}")

    item = {
        "itemType": "preprint",
        "id": make_safe_connector_id(arxiv_id),
        "title": paper_title(paper),
        "abstractNote": paper_summary(paper),
        "date": paper_date(paper),
        "language": "en",
        "libraryCatalog": "arXiv.org",
        "url": paper_arxiv_url(paper, arxiv_id),
        "accessDate": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "extra": "\n".join(extra_lines),
        "DOI": f"10.48550/arXiv.{arxiv_id}",
        "repository": "arXiv",
        "archiveID": f"arXiv:{arxiv_id}",
        "creators": creator_dicts(paper.get("authors")),
        "tags": [{"tag": category} for category in categories],
        "attachments": [],
    }
    return {key: value for key, value in item.items() if value not in ("", [], None)}


def item_matches_arxiv(data: dict[str, Any], arxiv_id: str) -> bool:
    normalized = normalize_arxiv_id(arxiv_id)
    values = [
        data.get("archiveID"),
        data.get("DOI"),
        data.get("url"),
        data.get("extra"),
        data.get("title"),
    ]
    haystack = "\n".join(str(value) for value in values if value)
    return normalize_arxiv_id(haystack) == normalized or normalized in haystack


def find_existing_item(client: HttpClient, arxiv_id: str, title: str | None = None) -> dict[str, Any] | None:
    queries = [arxiv_id, f"arXiv:{arxiv_id}", f"10.48550/arXiv.{arxiv_id}"]
    if title:
        queries.append(title)

    seen: set[str] = set()
    for query_text in queries:
        params = urllib.parse.urlencode({"q": query_text, "include": "data", "limit": 100})
        try:
            matches = client.api_json(f"{LOCAL_USER}/items/top?{params}")
        except ZoteroSyncError:
            continue
        if not isinstance(matches, list):
            continue
        for item in matches:
            key = item.get("key")
            if not key or key in seen:
                continue
            seen.add(key)
            data = item.get("data") if isinstance(item.get("data"), dict) else {}
            if item_matches_arxiv(data, arxiv_id):
                return item
    return None


def export_item_bibtex_key(client: HttpClient, item_key: str) -> str:
    text, _ = client.api_text_with_headers(f"{LOCAL_USER}/items/{urllib.parse.quote(item_key)}?format=bibtex")
    keys = extract_bibtex_keys(text)
    if not keys:
        raise ZoteroSyncError(f"Could not extract BibTeX key for Zotero item {item_key}")
    return keys[0]


def item_children(client: HttpClient, item_key: str) -> list[dict[str, Any]]:
    children: list[dict[str, Any]] = []
    start = 0
    limit = 100
    quoted_key = urllib.parse.quote(item_key)
    while True:
        params = urllib.parse.urlencode({"include": "data", "limit": limit, "start": start})
        text, headers = client.api_text_with_headers(f"{LOCAL_USER}/items/{quoted_key}/children?{params}")
        batch = json.loads(text or "[]")
        if not isinstance(batch, list):
            raise ZoteroSyncError(f"Unexpected Zotero children response for item {item_key}")
        children.extend(child for child in batch if isinstance(child, dict))

        total_raw = headers.get("Total-Results")
        total = int(total_raw) if total_raw and total_raw.isdigit() else None
        start += limit
        if total is not None and start >= total:
            break
        if total is None and len(batch) < limit:
            break
    return children


def child_data(child: dict[str, Any]) -> dict[str, Any]:
    data = child.get("data")
    return data if isinstance(data, dict) else {}


def child_is_pdf_attachment(child: dict[str, Any], arxiv_id: str = "") -> bool:
    data = child_data(child)
    if data.get("itemType") != "attachment":
        return False
    content_type = first_text(data.get("contentType")).lower()
    title = first_text(data.get("title")).lower()
    url = first_text(data.get("url")).lower()
    filename = first_text(data.get("filename")).lower()
    haystack = "\n".join([content_type, title, url, filename])
    return (
        content_type == "application/pdf"
        or content_type.endswith("/pdf")
        or ".pdf" in haystack
        or bool(arxiv_id and f"/pdf/{arxiv_id}" in haystack)
    )


def pdf_attachment_summary(child: dict[str, Any]) -> dict[str, Any]:
    data = child_data(child)
    return {
        "key": child.get("key") or data.get("key"),
        "title": first_text(data.get("title")),
        "content_type": first_text(data.get("contentType")),
        "url": first_text(data.get("url")),
        "filename": first_text(data.get("filename")),
    }


def item_pdf_status(client: HttpClient, item_key: str, arxiv_id: str = "") -> dict[str, Any]:
    children = item_children(client, item_key)
    pdfs = [pdf_attachment_summary(child) for child in children if child_is_pdf_attachment(child, arxiv_id)]
    return {
        "checked": True,
        "ok": bool(pdfs),
        "attachment_count": len(children),
        "pdf_count": len(pdfs),
        "attachments": pdfs,
    }


def wait_for_pdf_status(
    client: HttpClient,
    item_key: str,
    arxiv_id: str,
    *,
    timeout: float = 15.0,
    interval: float = 0.5,
) -> dict[str, Any]:
    deadline = time.time() + timeout
    last_status: dict[str, Any] = {"checked": False, "ok": False}
    while True:
        last_status = item_pdf_status(client, item_key, arxiv_id)
        if last_status.get("ok") or time.time() >= deadline:
            return last_status
        time.sleep(interval)


def collection_bibtex_keys(client: HttpClient, collection_key: str) -> list[str]:
    keys: list[str] = []
    seen: set[str] = set()
    start = 0
    limit = 100
    while True:
        params = urllib.parse.urlencode(
            {"format": "bibtex", "limit": limit, "start": start, "sort": "title", "direction": "asc"}
        )
        text, headers = client.api_text_with_headers(
            f"{LOCAL_USER}/collections/{urllib.parse.quote(collection_key)}/items/top?{params}"
        )
        for key in extract_bibtex_keys(text):
            if key not in seen:
                keys.append(key)
                seen.add(key)
        total_raw = headers.get("Total-Results")
        total = int(total_raw) if total_raw and total_raw.isdigit() else None
        start += limit
        if total is not None and start >= total:
            break
        if total is None and len(extract_bibtex_keys(text)) < limit:
            break
    return keys


def list_collections(client: HttpClient) -> list[dict[str, Any]]:
    data = client.api_json(f"{LOCAL_USER}/collections")
    if not isinstance(data, list):
        raise ZoteroSyncError("Unexpected Zotero collections response")
    return [collection.get("data", collection) for collection in data if isinstance(collection, dict)]


def find_collection_key(collections: list[dict[str, Any]], name: str, parent_key: str | bool | None) -> str | None:
    for collection in collections:
        if collection.get("name") == name and collection.get("parentCollection") == parent_key:
            key = first_text(collection.get("key"))
            if key:
                return key
    return None


def ensure_zotero_ready(client: HttpClient) -> dict[str, Any]:
    api_status, api_headers, _ = client.request("/api/", headers=API_HEADERS, timeout=5)
    connector_status, connector_headers, _ = client.connector_post("/connector/ping", {}, timeout=5)
    bbt = client.bbt_rpc("api.ready")
    return {
        "api_status": api_status,
        "connector_status": connector_status,
        "zotero_version": api_headers.get("X-Zotero-Version") or connector_headers.get("X-Zotero-Version"),
        "better_bibtex": bbt,
    }


def import_paper(
    client: HttpClient,
    paper: dict[str, Any],
    arxiv_id: str,
    *,
    download_pdf: bool,
    pdf_timeout: float,
    strict_pdf: bool,
) -> dict[str, Any]:
    session = f"codex-daily-arxiv-{re.sub(r'[^0-9]', '', arxiv_id)}-{int(time.time())}"
    item = connector_item_from_paper(paper, arxiv_id)
    arxiv_url = paper_arxiv_url(paper, arxiv_id)
    status, _, body = client.connector_post(
        "/connector/saveItems",
        {"sessionID": session, "uri": arxiv_url, "items": [item]},
        timeout=60,
    )
    if status not in {200, 201}:
        raise ZoteroSyncError(f"saveItems returned status={status} body={body[:TEXT_LIMIT]}")

    pdf_result: dict[str, Any] = {"attempted": False}
    if download_pdf:
        pdf_result["attempted"] = True
        pdf_url = paper_pdf_url(paper, arxiv_id)
        try:
            with urllib.request.urlopen(pdf_url, timeout=pdf_timeout) as response:
                pdf_data = response.read()
            metadata = {
                "sessionID": session,
                "parentItemID": item["id"],
                "title": "Full Text PDF",
                "url": pdf_url,
            }
            attach_status, _, attach_body = client.connector_post(
                f"/connector/saveAttachment?{urllib.parse.urlencode({'sessionID': session})}",
                pdf_data,
                content_type="application/pdf",
                headers={"X-Metadata": json.dumps(metadata)},
                timeout=max(60.0, pdf_timeout),
            )
            if attach_status not in {200, 201, 202}:
                raise ZoteroSyncError(
                    f"saveAttachment returned status={attach_status} body={attach_body[:TEXT_LIMIT]}"
                )
            pdf_result.update({"ok": True, "bytes": len(pdf_data), "url": pdf_url})
        except Exception as exc:
            pdf_result.update({"ok": False, "error": str(exc), "url": pdf_url})
            if strict_pdf:
                raise

    # Zotero indexing is asynchronous; poll briefly for the item to appear.
    title = paper_title(paper)
    for _ in range(20):
        match = find_existing_item(client, arxiv_id, title)
        if match:
            item_key = first_text(match.get("key"))
            if not item_key:
                raise ZoteroSyncError(f"Imported arXiv:{arxiv_id}, but Zotero returned an item without a key")
            if download_pdf:
                try:
                    pdf_status = wait_for_pdf_status(client, item_key, arxiv_id)
                    pdf_result["verified"] = bool(pdf_status.get("ok"))
                    pdf_result["status"] = pdf_status
                    if strict_pdf and not pdf_status.get("ok"):
                        raise ZoteroSyncError(f"PDF attachment was not found for imported arXiv:{arxiv_id}")
                except Exception as exc:
                    pdf_result["verified"] = False
                    pdf_result["verification_error"] = str(exc)
                    if strict_pdf:
                        raise
            return {
                "session": session,
                "item_key": item_key,
                "bibtex_key": export_item_bibtex_key(client, item_key),
                "pdf": pdf_result,
            }
        time.sleep(0.5)
    raise ZoteroSyncError(f"Imported arXiv:{arxiv_id}, but could not find it in Zotero after polling")


def write_aux(path: Path, citekeys: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["\\relax"]
    for key in citekeys:
        lines.append(f"\\citation{{{key}}}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_runtime_pdf_script(plan: list[dict[str, Any]]) -> str:
    plan_json = json.dumps(plan, ensure_ascii=True, indent=2)
    return RUNTIME_PDF_SCRIPT_TEMPLATE.replace("__PLAN_JSON__", plan_json)


def write_runtime_pdf_artifacts(
    *,
    plan: list[dict[str, Any]],
    plan_path: Path,
    script_path: Path,
) -> dict[str, Any]:
    plan_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    plan_path.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    script_path.write_text(render_runtime_pdf_script(plan), encoding="utf-8")
    return {
        "count": len(plan),
        "plan_path": str(plan_path),
        "script_path": str(script_path),
    }


def checkpoint_path_for_args(args: argparse.Namespace, date: str) -> Path | None:
    if not args.checkpoint_enabled:
        return None
    raw_path = args.checkpoint or f"work/zotero_sync_checkpoint_{date}.jsonl"
    return Path(raw_path).resolve()


def append_checkpoint_event(path: Path | None, event: dict[str, Any]) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(event, ensure_ascii=False, sort_keys=True) + "\n")
        handle.flush()


def load_checkpoint_completed(path: Path | None) -> dict[str, dict[str, Any]]:
    if path is None or not path.exists():
        return {}
    completed: dict[str, dict[str, Any]] = {}
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            if event.get("event") != "paper_completed":
                continue
            arxiv_id = first_text(event.get("arxiv_id"))
            result = event.get("result")
            if arxiv_id and isinstance(result, dict):
                completed[arxiv_id] = event
    return completed


def action_needs_runtime_pdf(action: dict[str, Any]) -> bool:
    pdf = action.get("pdf")
    return isinstance(pdf, dict) and bool(pdf.get("requires_runtime_attachment"))


def runtime_pdf_plan_entry(
    *,
    library_id: int,
    item_key: str,
    arxiv_id: str,
    title: str,
    paper: dict[str, Any],
) -> dict[str, Any]:
    return {
        "libraryID": library_id,
        "itemKey": item_key,
        "arxivId": arxiv_id,
        "title": title,
        "pdfUrl": paper_pdf_url(paper, arxiv_id),
        "referrer": paper_arxiv_url(paper, arxiv_id),
    }


def selected_arxiv_papers(payload: dict[str, Any], selection_payload: Any | None = None) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    selected = resolve_selected_papers(payload, selection_payload)
    papers: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in selected:
        paper = item["paper"]
        arxiv_id = arxiv_id_from_paper(paper)
        if not arxiv_id:
            skipped.append({"title": paper_title(paper), "reason": "missing arXiv id"})
            continue
        if arxiv_id in seen:
            continue
        seen.add(arxiv_id)
        papers.append(
            {
                "arxiv_id": arxiv_id,
                "title": paper_title(paper),
                "paper": paper,
                "topics": item.get("topics", []),
                "sources": paper.get("__sources", []),
                "indexes": paper.get("__indexes", []),
            }
        )
    return papers, skipped


def process_selected_paper(
    *,
    item: dict[str, Any],
    base_url: str,
    timeout: float,
    library_id: int,
    download_pdfs: bool,
    pdf_timeout: float,
    strict_pdf: bool,
) -> dict[str, Any]:
    client = HttpClient(base_url, timeout=timeout)
    arxiv_id = item["arxiv_id"]
    paper = item["paper"]
    runtime_plan_entry: dict[str, Any] | None = None

    match = find_existing_item(client, arxiv_id, item["title"])
    if match:
        item_key = first_text(match.get("key"))
        if not item_key:
            raise ZoteroSyncError(f"Matched arXiv:{arxiv_id}, but Zotero returned an item without a key")
        bibtex_key = export_item_bibtex_key(client, item_key)
        action = "already_in_zotero"
        pdf_status = item_pdf_status(client, item_key, arxiv_id)
        pdf_result = {
            "attempted": False,
            "checked": True,
            "ok": bool(pdf_status.get("ok")),
            "already_present": bool(pdf_status.get("ok")),
            "status": pdf_status,
        }
        if download_pdfs and not pdf_status.get("ok"):
            runtime_plan_entry = runtime_pdf_plan_entry(
                library_id=library_id,
                item_key=item_key,
                arxiv_id=arxiv_id,
                title=item["title"],
                paper=paper,
            )
            pdf_result.update(
                {
                    "requires_runtime_attachment": True,
                    "url": runtime_plan_entry["pdfUrl"],
                }
            )
        elif strict_pdf and not pdf_status.get("ok"):
            raise ZoteroSyncError(f"Existing Zotero item for arXiv:{arxiv_id} has no PDF attachment")
    else:
        imported_result = import_paper(
            client,
            paper,
            arxiv_id,
            download_pdf=download_pdfs,
            pdf_timeout=pdf_timeout,
            strict_pdf=strict_pdf,
        )
        item_key = imported_result["item_key"]
        bibtex_key = imported_result["bibtex_key"]
        action = "imported"
        pdf_result = imported_result["pdf"]
        if download_pdfs and not pdf_result.get("verified"):
            runtime_plan_entry = runtime_pdf_plan_entry(
                library_id=library_id,
                item_key=item_key,
                arxiv_id=arxiv_id,
                title=item["title"],
                paper=paper,
            )
            pdf_result["requires_runtime_attachment"] = True
            pdf_result.setdefault("url", runtime_plan_entry["pdfUrl"])

    action_record = {
        "action": action,
        "arxiv_id": arxiv_id,
        "title": item["title"],
        "zotero_item_key": item_key,
        "bibtex_key": bibtex_key,
        "topics": item["topics"],
        "pdf": pdf_result,
    }
    return {
        "arxiv_id": arxiv_id,
        "action_record": action_record,
        "runtime_pdf_plan_entry": runtime_plan_entry,
    }


def sync_selected_to_zotero(args: argparse.Namespace) -> dict[str, Any]:
    payload = load_json(args.input)
    if not isinstance(payload, dict):
        raise TypeError("Input JSON must be an object.")
    selection_payload = load_json(args.selection) if args.selection else None
    date = first_text(args.date, payload.get("date"), payload.get("selectedDate"))
    if not date:
        date = dt.date.today().isoformat()

    papers, skipped = selected_arxiv_papers(payload, selection_payload)
    if args.limit is not None:
        papers = papers[: args.limit]

    client = HttpClient(args.base_url, timeout=args.timeout)
    target_path = f"/{args.library_id}/{args.root_collection}/{date}"

    report: dict[str, Any] = {
        "date": date,
        "target_collection_path": target_path,
        "input": str(Path(args.input).resolve()) if args.input != "-" else "-",
        "selected_arxiv_papers": len(papers),
        "skipped": skipped,
        "dry_run": not args.yes and not args.verify_pdfs_only,
        "verify_pdfs_only": args.verify_pdfs_only,
        "download_pdf": args.download_pdfs,
        "actions": [],
    }

    if not papers:
        report["message"] = "No selected papers with arXiv IDs."
        return report

    if args.yes or args.check_zotero or args.verify_pdfs_only:
        report["zotero"] = ensure_zotero_ready(client)

    if args.verify_pdfs_only:
        missing_pdf: list[dict[str, Any]] = []
        for item in papers:
            arxiv_id = item["arxiv_id"]
            match = find_existing_item(client, arxiv_id, item["title"])
            if not match:
                missing = {
                    "arxiv_id": arxiv_id,
                    "title": item["title"],
                    "reason": "missing Zotero item",
                }
                missing_pdf.append(missing)
                report["actions"].append({"action": "verify_pdf", **missing, "pdf": {"checked": False, "ok": False}})
                continue
            item_key = first_text(match.get("key"))
            if not item_key:
                missing = {
                    "arxiv_id": arxiv_id,
                    "title": item["title"],
                    "reason": "Zotero item has no key",
                }
                missing_pdf.append(missing)
                report["actions"].append({"action": "verify_pdf", **missing, "pdf": {"checked": False, "ok": False}})
                continue
            pdf_status = item_pdf_status(client, item_key, arxiv_id)
            action = {
                "action": "verify_pdf",
                "arxiv_id": arxiv_id,
                "title": item["title"],
                "zotero_item_key": item_key,
                "pdf": pdf_status,
            }
            report["actions"].append(action)
            if not pdf_status.get("ok"):
                missing_pdf.append(
                    {
                        "arxiv_id": arxiv_id,
                        "title": item["title"],
                        "zotero_item_key": item_key,
                        "reason": "missing PDF attachment",
                    }
                )
        report["pdf_missing_after_verify"] = missing_pdf
        if missing_pdf and args.strict_pdf:
            raise ZoteroSyncError(f"PDF verification failed for {len(missing_pdf)} selected paper(s)", report)
        return report

    if not args.yes:
        report["actions"] = [
            {
                "action": "would_sync",
                "arxiv_id": item["arxiv_id"],
                "title": item["title"],
                "topics": item["topics"],
                "indexes": item["indexes"],
            }
            for item in papers
        ]
        return report

    collections = list_collections(client)
    root_key = find_collection_key(collections, args.root_collection, False)
    if not root_key:
        raise ZoteroSyncError(f"Root collection not found: {args.root_collection}")
    date_key = find_collection_key(collections, date, root_key)
    existing_citekeys = collection_bibtex_keys(client, date_key) if date_key else []

    citekeys = list(existing_citekeys)
    citekey_set = set(citekeys)
    checkpoint_path = checkpoint_path_for_args(args, date)
    completed_checkpoint = load_checkpoint_completed(checkpoint_path) if args.resume else {}
    resumed_from_checkpoint = 0
    failures: list[dict[str, Any]] = []
    action_slots: dict[int, dict[str, Any]] = {}
    runtime_pdf_plan_by_key: dict[str, dict[str, Any]] = {}

    report["checkpoint"] = {
        "enabled": checkpoint_path is not None,
        "path": str(checkpoint_path) if checkpoint_path else None,
        "resume": bool(args.resume),
        "completed_loaded": len(completed_checkpoint),
    }
    report["workers"] = max(1, int(args.workers))

    def remember_result(order: int, result: dict[str, Any], *, from_checkpoint: bool = False) -> None:
        nonlocal resumed_from_checkpoint
        action_record = dict(result["action_record"])
        if from_checkpoint:
            action_record["resumed_from_checkpoint"] = True
            resumed_from_checkpoint += 1
        action_slots[order] = action_record

        bibtex_key = first_text(action_record.get("bibtex_key"))
        if bibtex_key and bibtex_key not in citekey_set:
            citekeys.append(bibtex_key)
            citekey_set.add(bibtex_key)

        plan_entry = result.get("runtime_pdf_plan_entry")
        if isinstance(plan_entry, dict):
            plan_key = f"{plan_entry.get('libraryID')}:{plan_entry.get('itemKey')}:{plan_entry.get('pdfUrl')}"
            runtime_pdf_plan_by_key[plan_key] = plan_entry

    pending_jobs: list[tuple[int, dict[str, Any]]] = []
    for order, item in enumerate(papers):
        checkpoint_event = completed_checkpoint.get(item["arxiv_id"])
        if checkpoint_event:
            checkpoint_result = {
                "action_record": checkpoint_event["result"],
                "runtime_pdf_plan_entry": checkpoint_event.get("runtime_pdf_plan_entry"),
            }
            remember_result(order, checkpoint_result, from_checkpoint=True)
            progress_log(args.progress, f"[resume] {item['arxiv_id']} {item['title']}")
        else:
            pending_jobs.append((order, item))

    max_workers = max(1, int(args.workers))
    if pending_jobs:
        progress_log(args.progress, f"[sync] processing {len(pending_jobs)} paper(s) with workers={max_workers}")

    def record_failure(order: int, item: dict[str, Any], exc: Exception) -> None:
        failure = {
            "arxiv_id": item["arxiv_id"],
            "title": item["title"],
            "order": order,
            "error": str(exc),
        }
        failures.append(failure)
        append_checkpoint_event(
            checkpoint_path,
            {
                "event": "paper_failed",
                "date": date,
                "arxiv_id": item["arxiv_id"],
                "title": item["title"],
                "order": order,
                "timestamp": utc_now_iso(),
                "error": str(exc),
            },
        )
        progress_log(args.progress, f"[fail] {item['arxiv_id']} {exc}")

    def record_completed(order: int, item: dict[str, Any], result: dict[str, Any]) -> None:
        remember_result(order, result)
        append_checkpoint_event(
            checkpoint_path,
            {
                "event": "paper_completed",
                "date": date,
                "arxiv_id": item["arxiv_id"],
                "title": item["title"],
                "order": order,
                "timestamp": utc_now_iso(),
                "result": result["action_record"],
                "runtime_pdf_plan_entry": result.get("runtime_pdf_plan_entry"),
            },
        )
        progress_log(args.progress, f"[done] {item['arxiv_id']} {result['action_record']['action']}")

    def checkpoint_started(order: int, item: dict[str, Any]) -> None:
        append_checkpoint_event(
            checkpoint_path,
            {
                "event": "paper_started",
                "date": date,
                "arxiv_id": item["arxiv_id"],
                "title": item["title"],
                "order": order,
                "timestamp": utc_now_iso(),
            },
        )
        progress_log(args.progress, f"[start] {item['arxiv_id']} {item['title']}")

    if max_workers == 1:
        for order, item in pending_jobs:
            checkpoint_started(order, item)
            try:
                result = process_selected_paper(
                    item=item,
                    base_url=args.base_url,
                    timeout=args.timeout,
                    library_id=args.library_id,
                    download_pdfs=args.download_pdfs,
                    pdf_timeout=args.pdf_timeout,
                    strict_pdf=args.strict_pdf,
                )
                record_completed(order, item, result)
            except Exception as exc:
                record_failure(order, item, exc)
    elif pending_jobs:
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_to_job: dict[concurrent.futures.Future[dict[str, Any]], tuple[int, dict[str, Any]]] = {}
            for order, item in pending_jobs:
                checkpoint_started(order, item)
                future = executor.submit(
                    process_selected_paper,
                    item=item,
                    base_url=args.base_url,
                    timeout=args.timeout,
                    library_id=args.library_id,
                    download_pdfs=args.download_pdfs,
                    pdf_timeout=args.pdf_timeout,
                    strict_pdf=args.strict_pdf,
                )
                future_to_job[future] = (order, item)

            for future in concurrent.futures.as_completed(future_to_job):
                order, item = future_to_job[future]
                try:
                    record_completed(order, item, future.result())
                except Exception as exc:
                    record_failure(order, item, exc)

    report["actions"] = [action_slots[index] for index in sorted(action_slots)]
    imported = sum(1 for action in report["actions"] if action.get("action") == "imported")
    existing = sum(1 for action in report["actions"] if action.get("action") == "already_in_zotero")
    runtime_pdf_plan = list(runtime_pdf_plan_by_key.values())

    runtime_pdf_artifacts: dict[str, Any] | None = None
    if runtime_pdf_plan and args.runtime_pdf_helper:
        runtime_pdf_artifacts = write_runtime_pdf_artifacts(
            plan=runtime_pdf_plan,
            plan_path=Path(args.runtime_pdf_plan_out or f"work/zotero_attach_missing_pdfs_{date}.json").resolve(),
            script_path=Path(args.runtime_pdf_script_out or f"work/zotero_attach_missing_pdfs_{date}.js").resolve(),
        )
    elif runtime_pdf_plan:
        runtime_pdf_artifacts = {"count": len(runtime_pdf_plan), "disabled": True}

    aux_path = Path(args.aux_out or f"work/zotero_daily_papers_{date}.aux").resolve()
    write_aux(aux_path, citekeys)
    bbt_result = client.bbt_rpc("collection.scanAUX", [target_path, str(aux_path)])

    collections_after = list_collections(client)
    date_key_after = find_collection_key(collections_after, date, root_key) or (
        bbt_result.get("key") if isinstance(bbt_result, dict) else None
    )
    final_citekeys = collection_bibtex_keys(client, date_key_after) if date_key_after else []
    missing_after = sorted(citekey_set - set(final_citekeys))

    report.update(
        {
            "root_collection_key": root_key,
            "date_collection_key": date_key_after,
            "existing_before": len(existing_citekeys),
            "already_in_zotero": existing,
            "imported": imported,
            "resumed_from_checkpoint": resumed_from_checkpoint,
            "processed_successfully": len(report["actions"]),
            "failed": len(failures),
            "failures": failures,
            "runtime_pdf_attachment_plan": runtime_pdf_artifacts
            or {"count": 0, "plan_path": None, "script_path": None},
            "aux_path": str(aux_path),
            "better_bibtex_result": bbt_result,
            "final_collection_bibtex_keys": len(final_citekeys),
            "missing_after_sync": missing_after,
        }
    )
    if failures:
        raise ZoteroSyncError(f"Zotero processing failed for {len(failures)} selected paper(s)", report)
    if missing_after:
        raise ZoteroSyncError(f"Collection sync verification failed; missing citekeys: {missing_after}", report)
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync selected daily arXiv papers from Paper Easy JSON to Zotero."
    )
    parser.add_argument("--input", "-i", required=True, help="Daily brief input JSON.")
    parser.add_argument("--selection", "-s", help="Optional selected-index JSON override.")
    parser.add_argument("--date", help="Override target date collection name. Defaults to input date.")
    parser.add_argument("--root-collection", default=DEFAULT_ROOT_COLLECTION)
    parser.add_argument("--library-id", type=int, default=1, help="Better BibTeX library ID. Default: 1.")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--timeout", type=float, default=30.0)
    parser.add_argument("--pdf-timeout", type=float, default=90.0)
    parser.add_argument("--aux-out", help="Path for generated AUX file.")
    parser.add_argument("--runtime-pdf-plan-out", help="Path for generated missing-PDF attachment plan JSON.")
    parser.add_argument("--runtime-pdf-script-out", help="Path for generated Zotero runtime PDF attachment JS.")
    parser.add_argument("--limit", type=int, help="Only process the first N selected arXiv papers.")
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of selected papers to process concurrently. Default: 1.",
    )
    parser.add_argument(
        "--checkpoint",
        help="Append-only JSONL checkpoint path. Defaults to work/zotero_sync_checkpoint_<date>.jsonl.",
    )
    parser.add_argument(
        "--no-checkpoint",
        action="store_false",
        dest="checkpoint_enabled",
        help="Disable checkpoint JSONL writes.",
    )
    parser.add_argument(
        "--no-resume",
        action="store_false",
        dest="resume",
        help="Ignore existing checkpoint completed records and reprocess all selected papers.",
    )
    parser.add_argument(
        "--progress",
        action="store_true",
        help="Stream per-paper progress to stderr without corrupting stdout JSON.",
    )
    parser.add_argument("--check-zotero", action="store_true", help="Probe Zotero even in dry-run mode.")
    parser.add_argument(
        "--verify-pdfs-only",
        action="store_true",
        help="Only verify that selected arXiv papers already have Zotero PDF attachments.",
    )
    parser.add_argument("--yes", action="store_true", help="Actually write to Zotero. Without this, dry-run only.")
    parser.add_argument(
        "--no-pdf",
        action="store_false",
        dest="download_pdfs",
        help="Do not download/import PDFs. Metadata will still be imported.",
    )
    parser.add_argument(
        "--strict-pdf",
        action="store_true",
        help="Fail if direct PDF import or --verify-pdfs-only PDF verification fails.",
    )
    parser.add_argument(
        "--no-runtime-pdf-helper",
        action="store_false",
        dest="runtime_pdf_helper",
        help="Do not generate a Zotero runtime JS helper for existing items that are missing PDFs.",
    )
    parser.set_defaults(download_pdfs=True, runtime_pdf_helper=True, checkpoint_enabled=True, resume=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        report = sync_selected_to_zotero(args)
    except ZoteroSyncError as exc:
        payload: dict[str, Any] = {"ok": False, "error": str(exc)}
        if exc.report is not None:
            payload["result"] = exc.report
        dump_json(payload)
        return 1
    except Exception as exc:
        dump_json({"ok": False, "error": str(exc)})
        return 1
    dump_json({"ok": True, "result": report})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
